### ISSUE TITLE
MacOs - cannot run

### ISSUE THREAD

**Issue by AlexanderEsin** [RocketJumpTechnology/King-under-the-Mountain-Issue-Tracking#18]
Hi Ross,

Failing to get KUtM to run on either of my two Mac systems (El Capitan & Sierra).

Whichever way I run it, the same error (below). At best, the game blackscreens and crashes with error. At worst the game blackscreens with no way out except for a hard reset (tried on multiple attempts). My woeful Java and slightly better reading skills suggests that it's something to do with the WaterRenderer :)

All the best,

Alex

```
Using bundle resource folder [1]: /Users/aesin/Downloads/Contents/Resources/[King under the Mountain]
Loading JVM runtime library ...
Passing VM options ...
  # -Xms512m
Creating Java VM ...
Passing command line arguments ...
Loading JAR file ...
Invoking static technology.rocketjump.undermount.launcher.DesktopLauncher.main() function ...
2018-02-20 13:35:43.428 King under the Mountain[664:11688] 13:35:43.427 WARNING:  140: This application, or a library it uses, is using the deprecated Carbon Component Manager for hosting Audio Units. Support for this will be removed in a future release. Also, this makes the host incompatible with version 3 audio units. Please transition to the API's in AudioComponent.h.
Exception in thread "LWJGL Application" com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error injecting constructor, java.lang.IllegalArgumentException: couldn't compile shader: ERROR: 0:21: '*' does not operate on 'float' and 'int'
ERROR: 0:42: '-' does not operate on 'int' and 'float'
ERROR: 0:43: '-' does not operate on 'int' and 'float'
ERROR: 0:44: '-' does not operate on 'int' and 'float'
ERROR: 0:45: '-' does not operate on 'int' and 'float'
ERROR: 0:47: Use of undeclared identifier 'lowerLeftContribution'
ERROR: 0:47: Use of undeclared identifier 'upperLeftContribution'
ERROR: 0:47: Use of undeclared identifier 'upperRightContribution'
ERROR: 0:47: Use of undeclared identifier 'lowerRightContribution'
ERROR: 0:50: Use of undeclared identifier 'lowerLeftContribution'
ERROR: 0:50: Use of undeclared identifier 'lowerLeftContribution'
ERROR: 0:51: Use of undeclared identifier 'upperLeftContribution'
ERROR: 0:51: Use of undeclared identifier 'upperLeftContribution'
ERROR: 0:52: Use of undeclared identifier 'upperRightContribution'
ERROR: 0:52: Use of undeclared identifier 'upperRightContribution'
ERROR: 0:53: Use of undeclared identifier 'lowerRightContribution'
ERROR: 0:53: Use of undeclared identifier 'lowerRightContribution'
ERROR: 0:53: Use of undeclared identifier 'totalContributions'

  at technology.rocketjump.undermount.rendering.WaterRenderer.<init>(WaterRenderer.java:28)
  at technology.rocketjump.undermount.rendering.WaterRenderer.class(WaterRenderer.java:20)
  while locating technology.rocketjump.undermount.rendering.WaterRenderer
    for parameter 3 at technology.rocketjump.undermount.rendering.WorldRenderer.<init>(WorldRenderer.java:50)
  while locating technology.rocketjump.undermount.rendering.WorldRenderer
    for parameter 2 at technology.rocketjump.undermount.rendering.GameRenderer.<init>(GameRenderer.java:66)
  while locating technology.rocketjump.undermount.rendering.GameRenderer

1 error
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1018)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1044)
	at technology.rocketjump.undermount.UndermountApplicationAdapter.create(UndermountApplicationAdapter.java:64)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:147)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:124)
Caused by: java.lang.IllegalArgumentException: couldn't compile shader: ERROR: 0:21: '*' does not operate on 'float' and 'int'
ERROR: 0:42: '-' does not operate on 'int' and 'float'
ERROR: 0:43: '-' does not operate on 'int' and 'float'
ERROR: 0:44: '-' does not operate on 'int' and 'float'
ERROR: 0:45: '-' does not operate on 'int' and 'float'
ERROR: 0:47: Use of undeclared identifier 'lowerLeftContribution'
ERROR: 0:47: Use of undeclared identifier 'upperLeftContribution'
ERROR: 0:47: Use of undeclared identifier 'upperRightContribution'
ERROR: 0:47: Use of undeclared identifier 'lowerRightContribution'
ERROR: 0:50: Use of undeclared identifier 'lowerLeftContribution'
ERROR: 0:50: Use of undeclared identifier 'lowerLeftContribution'
ERROR: 0:51: Use of undeclared identifier 'upperLeftContribution'
ERROR: 0:51: Use of undeclared identifier 'upperLeftContribution'
ERROR: 0:52: Use of undeclared identifier 'upperRightContribution'
ERROR: 0:52: Use of undeclared identifier 'upperRightContribution'
ERROR: 0:53: Use of undeclared identifier 'lowerRightContribution'
ERROR: 0:53: Use of undeclared identifier 'lowerRightContribution'
ERROR: 0:53: Use of undeclared identifier 'totalContributions'

	at technology.rocketjump.undermount.rendering.custom_libgdx.ShaderLoader.createShader(ShaderLoader.java:13)
	at technology.rocketjump.undermount.rendering.custom_libgdx.FlowingWaterSpriteBatch.<init>(FlowingWaterSpriteBatch.java:127)
	at technology.rocketjump.undermount.rendering.WaterRenderer.<init>(WaterRenderer.java:20)
	at technology.rocketjump.undermount.rendering.WaterRenderer$$FastClassByGuice$$c5301f55.newInstance(<generated>)
	at com.google.inject.internal.cglib.reflect.$FastConstructor.newInstance(FastConstructor.java:40)
	at com.google.inject.internal.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:61)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:108)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:88)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:269)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1066)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.Scopes$1$1.get(Scopes.java:65)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:107)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:88)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:269)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:107)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:88)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:269)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1009)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1059)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1005)
	... 4 more
Destroyed Java VM ...
```

**Comment by rossturner** [comment]
Wow this is a critical one, thanks Alex. That'll teach me for assuming cross-compatibility is always working due to using Java! Turns out this is a problem in the shader code (GLSL, not Java) which I'm guessing must be stricter on Mac than Windows for some reason. 

I'll have to steal a Mac from someone then I'm sure I can get it sorted. Hopefully if the game ever brings in some decent funding I can afford a Mac for testing myself ;)

**Comment by AlexanderEsin** [comment]
Hi Ross,

I hope you don't mind - but I've got it to work. The issue seems to be the disparate declaration of float and integer literals in glsl between Windows and MacOS. A little bit of googling got me to
[this thread](https://github.com/gama-platform/gama/issues/1989) - and a gander at [this aptly named commit](https://github.com/gama-platform/gama/commit/2b88900bbb4992cc34965d3af9e04c7840de2b31) led me to simply change the integers in the assets/water/water_flow_fragment_shader.glsl at the error lines (commented) to produce the following updated shader file:

```
#ifdef GL_ES
    precision mediump float;
#endif

varying vec4 v_color;
varying vec2 v_lowerLeftFlow;
varying float v_distanceFromLowerLeft;
varying vec2 v_upperLeftFlow;
varying float v_distanceFromUpperLeft;
varying vec2 v_upperRightFlow;
varying float v_distanceFromUpperRight;
varying vec2 v_lowerRightFlow;
varying float v_distanceFromLowerRight;
varying vec2 v_texCoords0;
varying vec2 v_texCoords1;
uniform sampler2D u_texture0;
uniform sampler2D u_texture1;
uniform float u_time;

vec4 calculateContribution(in vec2 flow, in float nearness) {
    nearness = (nearness * nearness) * 2.0; // enhance contribution near to vertex rather than linear scale. AE: int > float
    vec2 texCoords0 = vec2(v_texCoords0.x, v_texCoords0.y); // Clone to avoid changing each time
    flow.x = -flow.x; // As glsl is upper-left origin

    flow *= u_time;

    vec4 wave_color = texture2D(u_texture1, fract(v_texCoords1 - flow));
    vec4 slower_wave_color = texture2D(u_texture1, fract(v_texCoords1 - (flow * 0.75)));

    texCoords0 = fract(texCoords0 + flow);

    float distortU = mix(texCoords0.x, wave_color.x, 0.1);
    float distortY = mix(texCoords0.y, slower_wave_color.y, 0.1);

    vec4 color_with_distortU = texture2D(u_texture0, fract(vec2(distortU, texCoords0.y)));
    vec4 color_with_distortY = texture2D(u_texture0, fract(vec2(texCoords0.x, distortY)));

    return vec4(mix(color_with_distortU, color_with_distortY, 0.5).rgb, nearness);
}

void main() {
    vec4 lowerLeftContribution = calculateContribution(v_lowerLeftFlow, clamp(1.0 - v_distanceFromLowerLeft, 0.0, 1.0)); // AE: int > float
    vec4 upperLeftContribution = calculateContribution(v_upperLeftFlow, clamp(1.0 - v_distanceFromUpperLeft, 0.0, 1.0)); // AE: int > float
    vec4 upperRightContribution = calculateContribution(v_upperRightFlow, clamp(1.0 - v_distanceFromUpperRight, 0.0, 1.0)); // AE: int > float
    vec4 lowerRightContribution = calculateContribution(v_lowerRightFlow, clamp(1.0 - v_distanceFromLowerRight, 0.0, 1.0)); // AE: int > float

    float totalContributions = lowerLeftContribution.a + upperLeftContribution.a + upperRightContribution.a + lowerRightContribution.a;

    gl_FragColor = vec4(
        ((lowerLeftContribution.rgb * lowerLeftContribution.a) +
        (upperLeftContribution.rgb * upperLeftContribution.a) +
        (upperRightContribution.rgb * upperRightContribution.a) +
        (lowerRightContribution.rgb * lowerRightContribution.a)) / totalContributions,
        1
    );
}
```

Lo, and behold - calling 
```
java -jar undermount-desktop.jar
```
launches just fine - with the sexy water flowing to boot!

Hopefully this will stave off having to acquire a Mac for a little while at least :)

Best,

Alex

**Comment by rossturner** [comment]
Of course I don't mind, that's fantastic, thanks Alex! I could see that the variable types were having some issues (still surprised it only was a problem on a Mac) but didn't know at a glance what to change it to, I'm still something of a beginner with GLSL as the fairly awful and inefficient code here shows! 

Thanks again, will get this updated into the next release.

**Comment by AlexanderEsin** [comment]
My pleasure - was good fun trying to figure it out. Yeah, not clear why Mac has to be weird - obviously worth making sure that the float changes don't affect the Win version and jury's out on the Linux...

**Comment by rossturner** [comment]
Fixed in pre-alpha 2 being released to Patreon on March 1st
