### ISSUE TITLE
"No OpenGL context found in the current thread" when toggling from fullscreen

### ISSUE THREAD

**Issue by rossturner** [RocketJumpTechnology/King-under-the-Mountain-Issue-Tracking#29]
Following the comments on https://www.reddit.com/r/KingUnderTheMountain/comments/86kkse/march_2018_update_ai_rewrite_and_heading_back_to/ a crash is happening for this user when they toggle from fullscreen.

Best option appears to be trying to post the screen change using https://github.com/libgdx/libgdx/wiki/Threading although it's difficult to tell without being able to reproduce the problem.

**Comment by rossturner** [comment]
Stack trace is
```
ERROR: java.lang.RuntimeException: No OpenGL context found in the current thread.
at org.lwjgl.opengl.GLContext.getCapabilities(GLContext.java:124)
at org.lwjgl.opengl.GL11.glClearColor(GL11.java:569)
at com.badlogic.gdx.backends.lwjgl.LwjglGL20.glClearColor(LwjglGL20.java:155)
at technology.rocketjump.undermount.UndermountApplicationAdapter.render(UndermountApplicationAdapter.java:116)
at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:223)
at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:124)
```

**Comment by rossturner** [comment]
Fullscreen toggling now requires the game to be restarted, which should avoid this issue
